# Generated by Django 5.0.3 on 2024-03-22 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('patients', models.JSONField()),
                ('SSN', models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Insurance',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('policy', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Med_Loc',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('med_type', models.CharField(choices=[('H', 'Hospital'), ('D', 'Drug Store'), ('C', 'Clinic')], max_length=1)),
                ('street_num', models.IntegerField(max_length=8)),
                ('street_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.IntegerField(max_length=8)),
                ('med_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.CharField(max_length=500)),
                ('status', models.BooleanField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='stationed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.med_loc'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('date_added', models.DateField(auto_now_add=True)),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('SSN', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('patientLocation', models.CharField(max_length=100)),
                ('street_num', models.IntegerField(max_length=8)),
                ('street_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.IntegerField(max_length=8)),
                ('bill', models.FloatField(max_length=15)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('health_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.health_insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('doctor_notes', models.CharField(max_length=500)),
                ('meds', models.JSONField()),
                ('allergies', models.JSONField()),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.appointment')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.doctor')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.patient'),
        ),
    ]
