# Generated by Django 5.0.3 on 2024-03-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='SSN',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='med_loc',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bill',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
