# Generated by Django 5.0.3 on 2024-03-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_doctor_ssn_alter_med_loc_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med_loc',
            name='street_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street_num',
            field=models.IntegerField(),
        ),
    ]
